# Generated by Django 2.2 on 2022-06-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='documents',
        ),
    ]
