# Generated by Django 2.2 on 2022-06-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_locate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='locate',
        ),
    ]
