# Generated by Django 2.2 on 2022-06-17 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_locate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='locate',
            new_name='loc',
        ),
    ]
