# Generated by Django 2.2 on 2022-06-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220615_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='type',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='user',
        ),
    ]
