# Generated by Django 2.2 on 2022-06-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220617_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loc',
            name='folder',
            field=models.CharField(default='new folder', max_length=15),
        ),
        migrations.AlterField(
            model_name='loc',
            name='type',
            field=models.CharField(default='type', max_length=10),
        ),
    ]
