# Generated by Django 2.2 on 2022-06-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_folders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='folders',
        ),
    ]
