# Generated by Django 2.2 on 2022-06-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_folders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loc',
            name='type',
        ),
    ]
