# Generated by Django 2.2 on 2022-06-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_loc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loc',
            name='file',
        ),
        migrations.RemoveField(
            model_name='loc',
            name='user',
        ),
        migrations.DeleteModel(
            name='document',
        ),
        migrations.DeleteModel(
            name='loc',
        ),
    ]
