# Generated by Django 2.2 on 2022-06-18 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 18, 29, 0, 214101)),
        ),
    ]
