# Generated by Django 2.2 on 2022-06-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220618_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='foldsize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('folder_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.folders')),
            ],
        ),
        migrations.DeleteModel(
            name='document',
        ),
    ]
