# Generated by Django 2.2 on 2022-06-18 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 23, 17, 39, 370244)),
        ),
        migrations.DeleteModel(
            name='foldsize',
        ),
    ]
