# Generated by Django 2.2 on 2022-06-18 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20220618_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 0, 17, 3, 191910)),
        ),
        migrations.DeleteModel(
            name='foldsize',
        ),
    ]
