# Generated by Django 2.2 on 2022-06-19 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20220619_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folders',
            old_name='size',
            new_name='s',
        ),
        migrations.AlterField(
            model_name='document',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 19, 41, 0, 723872)),
        ),
    ]
