# Generated by Django 2.2 on 2022-06-19 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20220619_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 20, 14, 41, 407714)),
        ),
        migrations.AlterField(
            model_name='folders',
            name='s',
            field=models.IntegerField(default=0),
        ),
    ]
