# Generated by Django 2.2 on 2022-06-20 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20220619_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 18, 30, 57, 190468)),
        ),
    ]
