# Generated by Django 2.2 on 2022-06-22 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20220622_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='perm_del',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 0, 22, 54, 252271)),
        ),
    ]
