# Generated by Django 2.2 on 2022-06-22 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20220623_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='perm_del',
            new_name='permanentdel',
        ),
        migrations.AlterField(
            model_name='document',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 0, 38, 14, 615984)),
        ),
    ]
