# Generated by Django 2.2 on 2022-06-27 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20220627_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='permanentdel',
        ),
        migrations.AlterField(
            model_name='document',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 16, 12, 25, 407399)),
        ),
    ]
