import json
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from store.models import documents

# Create your views here.

def register(request):
    if(request.method=="POST"):
        body=json.loads(request.body)
        x=User.objects.filter(username=body['user'])
        if(x.exists()):
            msg={'msg':'Username already exist'}
            return JsonResponse(msg, status=401, safe=False)
        user=User.objects.create_user(body['user'], body['mail'], body['pass1'])
        user.first_name=body['fname']
        user.last_name=body['lname']
        send_mail(
                'Confirmation Mail on registering succesfully on CloudBox',
                'This mail is send by the company CloudBox on succesfully registering on our server.\n\n\nThis message is generated by the server so do not reply back to it.',
                'sudhanshu.2125it1056@kiet.edu',
                [body['mail']],
                fail_silently=False
                 )
        msg={'msg':'Success'}
        user.save()
        return JsonResponse(msg, status=201, safe=False)


def log_in(request):
    if(request.method=="POST"):
        body=json.loads(request.body)
        user=authenticate(username=body['user'], password=body['pass1'])
        if(user is not None):
            login(request, user)
            print(user.id)
            request.session['id']=user.id
            msg={'msg':'Success'}
            return JsonResponse(msg, status=200, safe=False)
        else:
            msg={'msg':'Wrong credentials'}
            return JsonResponse(msg, status=401, safe=False)


def upload(request):
    if(request.method=="POST"):
        if(request.user.is_authenticated):
            body=request.FILES
            doc=documents(file=body['file'])
            doc.save()
            msg={'msg':'success'}
            return JsonResponse(msg, status=200, safe=False)


def out(request):
    logout(request)
    msg={'msg':'Logout successfull'}
    return JsonResponse(msg, status=200, safe=False)
